@extends('layouts.app')

@section('content')
<div class="container">
    <h1>Report Details</h1>

    <h3>Report Period: {{ $report->start_date }} to {{ $report->end_date }}</h3>
    <h4>Generated By: {{ $report->generatedBy->name }}</h4>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>User</th>
                <th>Total Tasks</th>
                <th>Completed Tasks</th>
                <th>Pending Tasks</th>
            </tr>
        </thead>
        <tbody>
            @foreach (json_decode($report->details, true) as $userId => $data)
				<tr>
					<td>{{ $data['user'] }}</td>
					<td>{{ $data['tasks'] }}</td>
					<td>{{ $data['completed'] }}</td>
					<td>{{ $data['tasks'] - $data['completed'] }}</td>
				</tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection
